### ISSUE TITLE
Git用語集作るよ

### ISSUE THREAD

**Issue by matsui-a** [466548/test#1]
ファイル追加するよ...
![寿司ゆき:sneak](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/18.png)

**Comment by matsui-a** [comment]
飽きたからやめた

![寿司ゆき:hide](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/19.png)

**Comment by 466548** [comment]
![寿司ゆき:oh_no](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/14.png)
